name: Cypress Tests

on:
  push:
  workflow_dispatch:

jobs:
  CI_E2E:
    runs-on: ubuntu-latest

    #TODO ADD
    # services:
    #   mongo:
    #     image: mongo:4.4
    #     env:
    #       MONGO_INITDB_DATABASE: testdb
    #     ports:
    #       - 27017:27017
    #     options: >-
    #       --health-cmd "mongo --eval 'db.runCommand({ ping: 1 })'"
    #       --health-interval 10s
    #       --health-timeout 5s
    #       --health-retries 5

    env:
      DATABASE_URL: #TODO ADD
      FAST_API_ENV: #TODO ADD
      PORT: 8080

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install backend dependencies
        run: |
          cd packages/backend
          python -m pip install --upgrade pip
          pip install flake8 pytest
          sudo npm install -g pyright
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run backend services
        run: |
          cd packages/backend
          python main.py &

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install frontend dependencies
        run: cd packages/frontend && npm install

      - name: Run frontend services
        run: |
          cd packages/frontend
          PORT=3000 npm run dev &

      - name: Print environment details
        run: |
          echo "Node.js version:"
          node -v
          echo "NPM version:"
          npm -v
          echo "Environment variables:"
          printenv

      - name: Install cypress dependencies
        run: |
          npm install

      # - name: Wait for services to be ready
      #   run: |
      #     npx wait-on http://localhost:3000
      #     npx wait-on http://localhost:8080

      - name: Run Cypress tests
        run: npm run cypress:run
